# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name ML_Zoomcamp2024 > environment.yml
#    conda env remove --name ML_Zoomcamp2024
#    conda env list

name: ML_Zoomcamp2024
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - black
  - flask
  - grpcio
  - gunicorn
  - isort
  - jupyterlab
  - matplotlib
  - numpy
  - pandas=2.2.3
  - pip
  - pipenv
  - pylint
  - python=3.11
  - requests
  - ruff
  - scikit-learn=1.5.2
  - seaborn
  - setuptools
  - tqdm
  - xgboost
  - pip:
    - scipy
    - keras-image-helper
    - tensorflow==2.17.1
    - tensorflow-metal==1.1.0
    - tensorflow-serving-api==2.7.0
    - torch
    - torchaudio
    - torchvision