# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml -y
#    conda env update --file environment.yml --prune
#    conda env export --name helloDogBreed > environment.yml
#    conda env remove --name helloDogBreed
#    conda env list

name: helloDogBreed
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - black
  - fiftyone
  - flask
  - grpcio
  - gunicorn
  - isort
  - jupyterlab
  - labelImg
  - matplotlib
  - mlflow
  - numpy<2.0
  - opencv
  - pandas
  - pillow
  - pip
  - pipenv
  - plotly
  - pycocotools
  - pylint
  - python=3.11
  - requests
  - ruff
  - scikit-learn=1.5.2
  - seaborn
  - setuptools
  - streamlit
  - supervision
  - tqdm
  - ultralytics
  - xgboost
  - lxml
  - pip:
    - albumentations
    - roboflow
    - fiftyone
    - keras-hub
    - keras-image-helper
    - label-studio
    - pylabel
    - scipy
    - tensorflow==2.17.1
    - tensorflow-metal==1.1.0
    - tensorflow-serving-api==2.7.0
    - torch
    - torchaudio
    - torchvision
